server:
  port: 9200

logging:
  config: classpath:log4j2-prod.xml
 
spring:
  config:
    activate:
      on-profile: prod
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':            
            allowedOrigins: "http://localhost:9090"
            allow-credentials: true
            allowedHeaders:
              - x-requested-with
              - authorization
              - content-type
              - credential
              - X-AUTH-TOKEN
              - X-CSRF-TOKEN
            allowedMethods:
              - POST
              - GET
              - PUT
              - OPTIONS
              - DELETE 
                           
file:
  path: /data/